[package]
name = "soroban-liquidity-pool-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "0.9.2", git = "https://github.com/stellar/rs-soroban-sdk", rev = "63cc30d5b09d396784a82aa7520f42015f146efd" }
num-integer = { version = "0.1.45", default-features = false, features = ["i128"] }

[dev_dependencies]
soroban-sdk = { version = "0.9.2", git = "https://github.com/stellar/rs-soroban-sdk", rev = "63cc30d5b09d396784a82aa7520f42015f146efd", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
